package openwrt

import (
	"context"
	"encoding/binary"
	"fmt"
	"log"
	"math/bits"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/design-maestro/fastlane/internal/domain"
)

const defaultFirewallRulesPath = "/tmp/fastlane-firewall.nft"

const (
	udpTProxyMark     = "0x1"
	udpTProxyMarkMask = "0x1"
	udpTProxyTable    = "100"
	udpTProxyPriority = "1000"
	probeBypassMark   = "0x100"

	minConntrackMax = 16384
	maxConntrackMax = 131072
)

var allLANSourceCIDRs = []string{
	"10.0.0.0/8",
	"172.16.0.0/12",
	"192.168.0.0/16",
}

var bypassDestinationCIDRs = []string{
	"0.0.0.0/8",
	"10.0.0.0/8",
	"100.64.0.0/10",
	"127.0.0.0/8",
	"169.254.0.0/16",
	"172.16.0.0/12",
	"192.168.0.0/16",
	"224.0.0.0/4",
	"240.0.0.0/4",
}

// FirewallRulesPath returns the nftables include generated by Fast Lane.
func FirewallRulesPath() string {
	if path := os.Getenv("FASTLANE_FIREWALL_RULES"); path != "" {
		return path
	}
	return defaultFirewallRulesPath
}

// FirewallManager applies transient nftables rules for transparent proxy routing.
type FirewallManager struct {
	NFTPath            string
	IPPath             string
	RulesPath          string
	DNSMasqPath        string
	DNSMasqServicePath string
	DNSMasqSnippetPath string
	ProcRoot           string
	MemInfoPath        string
	ConntrackMaxPath   string
	ConntrackCountPath string
}

type firewallPolicy struct {
	Mode             domain.FirewallMode
	DefaultAction    domain.FirewallDefaultAction
	SelectiveCapture bool
	CaptureSources   []string
	ExcludedSources  []string
	ProxyCIDRs       []string
	ProxyDomains     []string
	BypassCIDRs      []string
	BypassDomains    []string
}

// NewFirewallManager creates an OpenWrt nftables-based firewall manager.
func NewFirewallManager() FirewallManager {
	return FirewallManager{
		NFTPath:            "/usr/sbin/nft",
		IPPath:             "/sbin/ip",
		RulesPath:          FirewallRulesPath(),
		DNSMasqPath:        dnsmasqBinaryPath(),
		DNSMasqServicePath: dnsmasqServicePath(),
		DNSMasqSnippetPath: dnsmasqSnippetOverridePath(),
		ProcRoot:           "/proc",
	}
}

// Validate ensures the current platform supports the requested firewall mode.
func (m FirewallManager) Validate(ctx context.Context, settings domain.FirewallSettings) error {
	policy, err := resolveFirewallPolicy(settings)
	if err != nil {
		return err
	}
	if !policy.needsDNSMasqNFTSet() {
		return nil
	}
	if err := m.ensureDNSMasqNFTSetSupport(ctx); err != nil {
		return err
	}
	if _, err := m.dnsmasqSnippetPath(); err != nil {
		return err
	}
	return nil
}

// Apply renders and loads nftables rules.
func (m FirewallManager) Apply(ctx context.Context, settings domain.FirewallSettings) error {
	policy, err := resolveFirewallPolicy(settings)
	if err != nil {
		return err
	}
	if err := m.Validate(ctx, settings); err != nil {
		return err
	}
	if err := m.tuneConntrack(ctx); err != nil {
		return err
	}

	rules, err := BuildNFTablesRules(settings)
	if err != nil {
		return err
	}
	if err := atomicWriteText(m.RulesPath, rules, 0o644); err != nil {
		return fmt.Errorf("write firewall rules: %w", err)
	}

	m.cleanupPolicyRouting(ctx)
	_ = m.run(ctx, "delete", "table", "inet", "fastlane")
	if err := m.run(ctx, "-f", m.RulesPath); err != nil {
		return fmt.Errorf("apply nftables rules: %w", err)
	}
	if needsUDPPolicyRouting(settings) {
		if err := m.setupPolicyRouting(ctx); err != nil {
			_ = m.run(ctx, "delete", "table", "inet", "fastlane")
			m.cleanupPolicyRouting(ctx)
			return err
		}
	}

	if err := m.syncDNSMasqTargets(ctx, policy.ProxyDomainsForDNSMasq(), policy.BypassDomainsForDNSMasq()); err != nil {
		return fmt.Errorf("sync dnsmasq targets: %w", err)
	}

	return nil
}

type conntrackStats struct {
	Count      int
	Max        int
	Target     int
	Updated    bool
	ShouldWarn bool
}

// Disable removes the transient Fast Lane nftables table.
func (m FirewallManager) Disable(ctx context.Context) error {
	if err := m.tuneConntrack(ctx); err != nil {
		return err
	}
	m.cleanupPolicyRouting(ctx)
	err := m.run(ctx, "delete", "table", "inet", "fastlane")
	if err != nil && !strings.Contains(strings.ToLower(err.Error()), "no such file or directory") {
		return err
	}
	_ = os.Remove(m.RulesPath)
	if err := m.syncDNSMasqTargets(ctx, nil, nil); err != nil {
		return err
	}
	return nil
}

// BuildNFTablesRules returns an nftables ruleset for the provided targets.
func BuildNFTablesRules(settings domain.FirewallSettings) (string, error) {
	policy, err := resolveFirewallPolicy(settings)
	if err != nil {
		return "", err
	}
	hasProxyOutput := len(policy.ProxyCIDRs) > 0 || len(policy.ProxyDomains) > 0
	hasBypassOutput := len(policy.BypassCIDRs) > 0 || len(policy.BypassDomains) > 0
	udpSelector := transparentUDPSelector(settings)

	port := settings.TransparentPort
	if port <= 0 {
		port = 12345
	}

	var builder strings.Builder
	builder.WriteString("table inet fastlane {\n")
	if hasProxyOutput {
		builder.WriteString("  set proxy_target_v4 {\n    type ipv4_addr\n    flags interval\n")
		if len(policy.ProxyCIDRs) > 0 {
			fmt.Fprintf(&builder, "    elements = { %s }\n", strings.Join(policy.ProxyCIDRs, ", "))
		}
		builder.WriteString("  }\n\n")
	}
	if hasBypassOutput {
		builder.WriteString("  set direct_target_v4 {\n    type ipv4_addr\n    flags interval\n")
		if len(policy.BypassCIDRs) > 0 {
			fmt.Fprintf(&builder, "    elements = { %s }\n", strings.Join(policy.BypassCIDRs, ", "))
		}
		builder.WriteString("  }\n\n")
	}
	if len(policy.CaptureSources) > 0 {
		fmt.Fprintf(&builder, "  set source_v4 {\n    type ipv4_addr\n    flags interval\n    elements = { %s }\n  }\n\n", strings.Join(policy.CaptureSources, ", "))
		fmt.Fprintf(&builder, "  set local_bypass_v4 {\n    type ipv4_addr\n    flags interval\n    elements = { %s }\n  }\n\n", strings.Join(bypassDestinationCIDRs, ", "))
	}
	if len(policy.ExcludedSources) > 0 {
		fmt.Fprintf(&builder, "  set excluded_source_v4 {\n    type ipv4_addr\n    flags interval\n    elements = { %s }\n  }\n\n", strings.Join(policy.ExcludedSources, ", "))
	}

	builder.WriteString("  chain prerouting {\n    type nat hook prerouting priority dstnat; policy accept;\n")
	if len(policy.CaptureSources) > 0 {
		if len(policy.ExcludedSources) > 0 {
			builder.WriteString("    ip saddr @excluded_source_v4 return\n")
		}
		builder.WriteString("    ip daddr @local_bypass_v4 return\n")
		if hasBypassOutput {
			builder.WriteString("    ip daddr @direct_target_v4 return\n")
		}
		if policy.SelectiveCapture {
			if hasProxyOutput {
				fmt.Fprintf(&builder, "    ip saddr @source_v4 ip daddr @proxy_target_v4 tcp dport != %d redirect to :%d\n", port, port)
			}
		} else {
			fmt.Fprintf(&builder, "    ip saddr @source_v4 tcp dport != %d redirect to :%d\n", port, port)
		}
	}
	builder.WriteString("  }\n")

	if len(policy.CaptureSources) > 0 {
		builder.WriteString("\n  chain prerouting_mangle {\n    type filter hook prerouting priority mangle; policy accept;\n")
		if len(policy.ExcludedSources) > 0 {
			builder.WriteString("    ip saddr @excluded_source_v4 return\n")
		}
		builder.WriteString("    ip daddr @local_bypass_v4 return\n")
		if hasBypassOutput {
			builder.WriteString("    ip daddr @direct_target_v4 return\n")
		}
		if policy.SelectiveCapture {
			if hasProxyOutput {
				fmt.Fprintf(&builder, "    ip saddr @source_v4 ip daddr @proxy_target_v4 %s meta mark set %s tproxy ip to :%d accept\n", udpSelector, udpTProxyMark, port)
			}
		} else {
			fmt.Fprintf(&builder, "    ip saddr @source_v4 %s meta mark set %s tproxy ip to :%d accept\n", udpSelector, udpTProxyMark, port)
		}
		builder.WriteString("  }\n")
	}

	if hasProxyOutput {
		builder.WriteString("\n  chain output {\n    type nat hook output priority -100; policy accept;\n")
		fmt.Fprintf(&builder, "    meta mark %s return\n", probeBypassMark)
		if hasBypassOutput {
			builder.WriteString("    ip daddr @direct_target_v4 return\n")
		}
		fmt.Fprintf(&builder, "    ip daddr @proxy_target_v4 tcp dport != %d redirect to :%d\n  }\n", port, port)
	}

	builder.WriteString("}\n")
	return builder.String(), nil
}

func transparentUDPSelector(settings domain.FirewallSettings) string {
	if settings.BlockQUIC {
		return "udp dport 443"
	}
	return "meta l4proto udp"
}

func resolveFirewallPolicy(settings domain.FirewallSettings) (firewallPolicy, error) {
	settings = domain.CanonicalFirewallSettings(settings)
	policy := firewallPolicy{
		Mode:             domain.NormalizeFirewallMode(settings.Mode),
		DefaultAction:    domain.FirewallDefaultActionProxy,
		SelectiveCapture: false,
	}

	switch policy.Mode {
	case domain.FirewallModeHosts:
		sources, err := normalizeFirewallSources(settings.Hosts)
		if err != nil {
			return firewallPolicy{}, err
		}
		if len(sources) == 0 {
			return firewallPolicy{}, fmt.Errorf("at least one source host is required")
		}
		policy.CaptureSources = sources
	case domain.FirewallModeTargets:
		proxyCIDRs, err := normalizeFirewallTargets(domain.ExpandFirewallSelectorSetCIDRs(settings.TargetServiceCatalog, settings.Targets))
		if err != nil {
			return firewallPolicy{}, err
		}
		proxyDomains := domain.ExpandFirewallSelectorSetDomains(settings.TargetServiceCatalog, settings.Targets)
		captureSources, err := normalizeFirewallTargets(allLANSourceCIDRs)
		if err != nil {
			return firewallPolicy{}, err
		}
		if len(proxyCIDRs) == 0 && len(proxyDomains) == 0 {
			return firewallPolicy{}, fmt.Errorf("at least one proxy target is required")
		}
		policy.CaptureSources = captureSources
		policy.ProxyCIDRs = proxyCIDRs
		policy.ProxyDomains = proxyDomains
		policy.DefaultAction = domain.FirewallDefaultActionDirect
		policy.SelectiveCapture = true
	case domain.FirewallModeSplit:
		proxyCIDRs, err := normalizeFirewallTargets(domain.ExpandFirewallSelectorSetCIDRs(settings.TargetServiceCatalog, settings.Split.Proxy))
		if err != nil {
			return firewallPolicy{}, err
		}
		proxyDomains := domain.ExpandFirewallSelectorSetDomains(settings.TargetServiceCatalog, settings.Split.Proxy)
		bypassCIDRs, err := normalizeFirewallTargets(domain.ExpandFirewallSelectorSetCIDRs(settings.TargetServiceCatalog, settings.Split.Bypass))
		if err != nil {
			return firewallPolicy{}, err
		}
		bypassDomains := domain.ExpandFirewallSelectorSetDomains(settings.TargetServiceCatalog, settings.Split.Bypass)
		excludedSources, err := normalizeFirewallSources(settings.Split.ExcludedSources)
		if err != nil {
			return firewallPolicy{}, err
		}
		defaultAction := domain.NormalizeFirewallDefaultAction(settings.Split.DefaultAction)
		if len(proxyCIDRs) == 0 && len(proxyDomains) == 0 && len(bypassCIDRs) == 0 && len(bypassDomains) == 0 && defaultAction != domain.FirewallDefaultActionProxy {
			return firewallPolicy{}, fmt.Errorf("at least one split proxy or bypass target is required")
		}
		captureSources, err := normalizeFirewallTargets(allLANSourceCIDRs)
		if err != nil {
			return firewallPolicy{}, err
		}
		policy.CaptureSources = captureSources
		policy.ExcludedSources = excludedSources
		policy.ProxyCIDRs = proxyCIDRs
		policy.ProxyDomains = proxyDomains
		policy.BypassCIDRs = bypassCIDRs
		policy.BypassDomains = bypassDomains
		policy.DefaultAction = defaultAction
		policy.SelectiveCapture = policy.DefaultAction == domain.FirewallDefaultActionDirect
	default:
		return firewallPolicy{}, fmt.Errorf("at least one target service/domain/IP/CIDR or one source host is required")
	}

	return policy, nil
}

func (p firewallPolicy) needsDNSMasqNFTSet() bool {
	if len(p.ProxyDomains) > 0 {
		return true
	}
	hasProxyOutput := len(p.ProxyCIDRs) > 0 || len(p.ProxyDomains) > 0
	return len(p.BypassDomains) > 0 && (hasProxyOutput || p.DefaultAction == domain.FirewallDefaultActionProxy)
}

func (p firewallPolicy) ProxyDomainsForDNSMasq() []string {
	if !p.needsDNSMasqNFTSet() {
		return nil
	}
	return append([]string(nil), p.ProxyDomains...)
}

func (p firewallPolicy) BypassDomainsForDNSMasq() []string {
	if !p.needsDNSMasqNFTSet() {
		return nil
	}
	return append([]string(nil), p.BypassDomains...)
}

func normalizeFirewallTargets(targets []string) ([]string, error) {
	seen := make(map[string]struct{}, len(targets))
	out := make([]string, 0, len(targets))
	for _, target := range targets {
		target = strings.TrimSpace(target)
		if target == "" {
			continue
		}

		normalized, err := normalizeFirewallTarget(target)
		if err != nil {
			return nil, err
		}
		for _, item := range normalized {
			if _, ok := seen[item]; ok {
				continue
			}
			seen[item] = struct{}{}
			out = append(out, item)
		}
	}

	sort.Strings(out)
	return out, nil
}

func normalizeFirewallSources(sources []string) ([]string, error) {
	for _, source := range sources {
		if isAllFirewallSource(source) {
			return normalizeFirewallTargets(allLANSourceCIDRs)
		}
	}
	return normalizeFirewallTargets(sources)
}

func normalizeFirewallTarget(target string) ([]string, error) {
	switch {
	case parseIPv4(target), parseIPv4CIDR(target):
		return []string{target}, nil
	case strings.Contains(target, "-"):
		cidrs, err := expandIPv4Range(target)
		if err != nil {
			return nil, err
		}
		return cidrs, nil
	default:
		return nil, fmt.Errorf("unsupported target %q: only IPv4, IPv4 CIDR, and IPv4 ranges are supported", target)
	}
}

func (m FirewallManager) memInfoPath() string {
	return firstNonEmpty(m.MemInfoPath, filepath.Join(firstNonEmpty(m.ProcRoot, "/proc"), "meminfo"))
}

func (m FirewallManager) conntrackMaxPath() string {
	return firstNonEmpty(m.ConntrackMaxPath, filepath.Join(firstNonEmpty(m.ProcRoot, "/proc"), "sys", "net", "netfilter", "nf_conntrack_max"))
}

func (m FirewallManager) conntrackCountPath() string {
	return firstNonEmpty(m.ConntrackCountPath, filepath.Join(firstNonEmpty(m.ProcRoot, "/proc"), "sys", "net", "netfilter", "nf_conntrack_count"))
}

func (m FirewallManager) tuneConntrack(ctx context.Context) error {
	stats, err := m.autoTuneConntrack()
	if err != nil {
		log.Printf("fastlane: conntrack auto-tune skipped: %v", err)
		return nil
	}
	if stats.Updated {
		log.Printf("fastlane: conntrack limit raised to %d (count=%d)", stats.Max, stats.Count)
	}
	if stats.ShouldWarn {
		log.Printf("fastlane: conntrack usage is high count=%d max=%d", stats.Count, stats.Max)
	}
	_ = ctx
	return nil
}

func (m FirewallManager) autoTuneConntrack() (conntrackStats, error) {
	memTotalKiB, err := readMemTotalKiB(m.memInfoPath())
	if err != nil {
		return conntrackStats{}, err
	}

	currentMax, err := readIntFromFile(m.conntrackMaxPath())
	if err != nil {
		return conntrackStats{}, err
	}

	currentCount, err := readIntFromFile(m.conntrackCountPath())
	if err != nil {
		return conntrackStats{}, err
	}

	target := conntrackTargetForMemTotalKiB(memTotalKiB)
	stats := conntrackStats{
		Count:  currentCount,
		Max:    currentMax,
		Target: target,
	}

	if currentMax < target {
		if err := os.WriteFile(m.conntrackMaxPath(), []byte(fmt.Sprintf("%d\n", target)), 0o644); err != nil {
			return conntrackStats{}, err
		}
		stats.Max = target
		stats.Updated = true
	}

	if stats.Max > 0 && float64(stats.Count)/float64(stats.Max) >= 0.85 {
		stats.ShouldWarn = true
	}

	return stats, nil
}

func conntrackTargetForMemTotalKiB(memTotalKiB int) int {
	base := memTotalKiB / 4
	if base < 1 {
		base = 1
	}

	target := nextPowerOfTwo(base)
	if target < minConntrackMax {
		target = minConntrackMax
	}
	if target > maxConntrackMax {
		target = maxConntrackMax
	}
	return target
}

func nextPowerOfTwo(value int) int {
	if value <= 1 {
		return 1
	}
	return 1 << bits.Len(uint(value-1))
}

func readMemTotalKiB(path string) (int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0, err
	}

	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "MemTotal:") {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 2 {
			return 0, fmt.Errorf("parse %s: malformed MemTotal line", path)
		}

		value, err := strconv.Atoi(fields[1])
		if err != nil {
			return 0, fmt.Errorf("parse %s: %w", path, err)
		}
		return value, nil
	}

	return 0, fmt.Errorf("parse %s: MemTotal not found", path)
}

func readIntFromFile(path string) (int, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0, err
	}

	value, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil {
		return 0, fmt.Errorf("parse %s: %w", path, err)
	}
	return value, nil
}

func isAllFirewallSource(value string) bool {
	value = strings.TrimSpace(value)
	return strings.EqualFold(value, "all") || value == "*"
}

func parseIPv4(value string) bool {
	ip := net.ParseIP(value)
	return ip != nil && ip.To4() != nil
}

func parseIPv4CIDR(value string) bool {
	ip, _, err := net.ParseCIDR(value)
	return err == nil && ip.To4() != nil
}

func expandIPv4Range(value string) ([]string, error) {
	parts := strings.SplitN(value, "-", 2)
	if len(parts) != 2 {
		return nil, fmt.Errorf("invalid IPv4 range %q", value)
	}

	startIP := net.ParseIP(strings.TrimSpace(parts[0]))
	endIP := net.ParseIP(strings.TrimSpace(parts[1]))
	if startIP == nil || startIP.To4() == nil || endIP == nil || endIP.To4() == nil {
		return nil, fmt.Errorf("unsupported target %q: only IPv4, IPv4 CIDR, and IPv4 ranges are supported", value)
	}

	start := ipv4ToUint32(startIP)
	end := ipv4ToUint32(endIP)
	if start > end {
		return nil, fmt.Errorf("invalid IPv4 range %q: start must be <= end", value)
	}

	return ipv4RangeToCIDRs(start, end), nil
}

func ipv4RangeToCIDRs(start, end uint32) []string {
	var cidrs []string
	for start <= end {
		prefix := 32 - bits.TrailingZeros32(start)
		remaining := end - start + 1
		maxBlockPrefix := 32 - (bits.Len32(remaining) - 1)
		if prefix < maxBlockPrefix {
			prefix = maxBlockPrefix
		}

		cidrs = append(cidrs, fmt.Sprintf("%s/%d", uint32ToIPv4(start).String(), prefix))
		if prefix == 0 {
			break
		}
		step := uint64(1) << (32 - prefix)
		start = uint32(uint64(start) + step)
	}
	return cidrs
}

func ipv4ToUint32(ip net.IP) uint32 {
	return binary.BigEndian.Uint32(ip.To4())
}

func uint32ToIPv4(value uint32) net.IP {
	buf := make([]byte, 4)
	binary.BigEndian.PutUint32(buf, value)
	return net.IP(buf)
}

func (m FirewallManager) run(ctx context.Context, args ...string) error {
	cmd := exec.CommandContext(ctx, m.NFTPath, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w: %s", m.NFTPath, strings.Join(args, " "), err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (m FirewallManager) runIP(ctx context.Context, args ...string) error {
	cmd := exec.CommandContext(ctx, m.IPPath, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w: %s", m.IPPath, strings.Join(args, " "), err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (m FirewallManager) setupPolicyRouting(ctx context.Context) error {
	if err := m.runIP(ctx, "route", "add", "local", "0.0.0.0/0", "dev", "lo", "table", udpTProxyTable); err != nil {
		return fmt.Errorf("configure udp tproxy route: %w", err)
	}
	if err := m.runIP(ctx, "rule", "add", "fwmark", udpTProxyMark+"/"+udpTProxyMarkMask, "table", udpTProxyTable, "priority", udpTProxyPriority); err != nil {
		_ = m.runIP(ctx, "route", "del", "local", "0.0.0.0/0", "dev", "lo", "table", udpTProxyTable)
		return fmt.Errorf("configure udp tproxy rule: %w", err)
	}
	return nil
}

func (m FirewallManager) cleanupPolicyRouting(ctx context.Context) {
	_ = m.runIP(ctx, "rule", "del", "fwmark", udpTProxyMark+"/"+udpTProxyMarkMask, "table", udpTProxyTable, "priority", udpTProxyPriority)
	_ = m.runIP(ctx, "route", "del", "local", "0.0.0.0/0", "dev", "lo", "table", udpTProxyTable)
}

func needsUDPPolicyRouting(settings domain.FirewallSettings) bool {
	if !settings.Enabled {
		return false
	}

	policy, err := resolveFirewallPolicy(settings)
	return err == nil && len(policy.CaptureSources) > 0
}

func atomicWriteText(path, data string, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer func() { _ = os.Remove(tmpPath) }()

	if _, err := tmp.WriteString(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	return os.Rename(tmpPath, path)
}
