// Generated by scripts/sync-routing-panel.cjs from luci-app-fastlane/htdocs/luci-static/resources/view/fastlane/routing-20260906-v5.js.
// mount(container,{api,operation,notice,confirmAction,getSnapshot}) -> {ready,refresh,destroy}; root may call global refresh(snapshot).
(function installRoutingPanel(translations, makeScreen) {
  'use strict';
  let instance;
  const text = value => String(value == null ? '' : value).trim();
  const words = value => text(value).split(/[\s,;]+/).filter(Boolean);
  const _ = message => (document.documentElement.lang || 'en').toLowerCase().startsWith('ru') ? (translations[message] || message) : message;
  const errors = {
    geo_runtime_unavailable:'GeoIP/GeoSite доступны только со штатной службой OpenWrt. В локальном прототипе обновление недоступно.',
    geo_status_failed:'Не удалось прочитать состояние GeoIP/GeoSite.',
    geo_update_failed:'GeoIP/GeoSite не прошли проверку. Правило не включено.',
    geo_update_timeout:'Обновление ещё не завершилось. Проверьте состояние позже.',
    routing_group_exists:'Исключение с таким именем уже существует. Откройте его для редактирования.',
    routing_group_not_editable:'Исключение не найдено или доступно только для чтения.',
    invalid_routing_group:'Проверьте домены и IPv4-адреса, подсети или диапазоны.',
    routing_group_saved_activation_failed:'Группа сохранена, но применение не завершилось. Проверьте её состояние перед повтором.',
    routing_group_delete_failed:'Не удалось удалить группу. Возможно, она используется в других правилах или сохранённых настройках.',
    routing_groups_unavailable:'Список исключений недоступен. Повторите загрузку.',
    happ_atomic_apply_unavailable:translations['The link is valid. Partial application is disabled until Fast Lane can apply custom direct, proxy, and block rules atomically.'],
    operation_failed:'Операция не выполнена. Проверьте данные и состояние службы.'
  };
  const errorText = value => (document.documentElement.lang || '').startsWith('ru') ? (errors[value] || value) : ({geo_runtime_unavailable:'Geo databases require the OpenWrt runtime. Updates are unavailable on this local prototype.',operation_failed:'Operation failed. Check the data and service status.'}[value] || value);
  function E(tag, attributes = {}, children = []) {
    const element = document.createElement(tag);
    for (const [key, value] of Object.entries(attributes)) {
      if (value == null) continue;
      if (typeof value === 'function') element.addEventListener(key, value);
      else if (['checked','selected','disabled'].includes(key)) element[key] = Boolean(value);
      else if (key === 'value') element.value = value;
      else element.setAttribute(key, value);
    }
    for (const child of (Array.isArray(children) ? children : [children]).flat(Infinity)) {
      if (child != null) element.append(child instanceof Node ? child : document.createTextNode(String(child)));
    }
    return element;
  }
  const L = {bind:(fn, self, ...args) => fn.bind(self, ...args)};
  function mount(container, shared) {
    if (!container || !shared || typeof shared.api !== 'function' || typeof shared.confirmAction !== 'function' || !window.FastLaneCountries) throw Error('Routing requires container, shared API and legacy-countries.js');
    if (instance) instance.destroy();
    let stopped = false, modal = null, requestVersion = 0, fingerprint = '', pending = false, latestJob = null, needsRetry = false;
    const countries = {
      name:code => window.FastLaneCountries.name(code),
      options:selected => window.FastLaneCountries.codes.map(code => E('option', {value:code, selected:code===selected}, [window.FastLaneCountries.name(code)+' ('+code+')'])).sort((a,b) => a.textContent.localeCompare(b.textContent,document.documentElement.lang || 'en'))
    };
    const ui = {
      createHandlerFn:(self, method, ...args) => event => self[method](...args,event),
      showModal:(title, children) => {
        ui.hideModal();
        modal = E('dialog', {class:'modal fl-dialog', 'aria-label':title}, [E('h4',{},[title]), ...children]);
        const opened=modal;
        container.append(modal);
        modal.addEventListener('close', () => { if(modal===opened) modal=null; opened.remove(); });
        modal.showModal();
      },
      hideModal:() => { if (modal) { const old=modal; modal=null; old.close(); old.remove(); } }
    };
    const screen = makeScreen(E, _, L, ui, countries);
    const page = E('div',{class:'flr-page'});
    container.replaceChildren(page);
    const notice = (message, failed=false) => { if(!stopped) shared.notice(message, failed); };
    screen.settings = {};
    screen.services = [];
    screen.geodata = {ready:false};
    screen.busy = true;
    screen.progress = _('Preparing routing…');
    screen.renderAgain = () => {
      if (stopped) return;
      const expanded = page.querySelector('.flr-advanced')?.open;
      const oldInput = page.querySelector('.flr-import input');
      const focused = document.activeElement === oldInput;
      const selection = focused ? [oldInput.selectionStart,oldInput.selectionEnd] : null;
      page.replaceChildren(...screen.renderContent());
      const advanced = page.querySelector('.flr-advanced');
      advanced.open = !!expanded;
      if(focused) { const input = page.querySelector('.flr-import input'); input.focus(); input.setSelectionRange(...selection); }
      const progress = page.querySelector('.flr-progress');
      if(screen.geodata.error && !screen.progress) progress.textContent = errorText(screen.geodata.error);
      // Validation preview must remain visible when rendered after a request.
      if(screen.importProfile || screen.importError) advanced.open = true;
      const input = page.querySelector('.flr-import input');
      input.setAttribute('aria-label','HAPP');
      input.addEventListener('input', () => {
        screen.importProfile=null; screen.importError='';
        page.querySelector('.flr-preview')?.remove();
      });
      page.querySelectorAll('.flr-rule').forEach(article => {
        article.querySelector('input').setAttribute('aria-label', article.querySelector('h3').textContent);
      });
    };
    function acceptJob(job) { latestJob=job || latestJob; }
    async function load() {
      const version = ++requestVersion;
      try {
        const data = await shared.api('routing/state');
        if(stopped || version !== requestVersion) return;
        needsRetry=false;
        acceptJob(data.job);
        const next = JSON.stringify([data.country_routing,data.firewall,data.services,data.geo,data.rules_error,!!data.job?.running]);
        screen.settings = {country_routing:data.country_routing,firewall:data.firewall};
        screen.services = data.services || [];
        screen.geodata = data.geo || {ready:false};
        screen.rulesError = data.rules_error ? errorText(data.rules_error) : '';
        screen.countryCode = data.country_routing?.country_code || ({ru:'RU',zh:'CN',fa:'IR'}[(document.documentElement.lang || navigator.language || '').toLowerCase().split('-')[0]] || '');
        if(!pending) { screen.busy=!!data.job?.running; screen.progress=data.geo?.updating ? _('Downloading and validating GeoIP and GeoSite…') : ''; }
        if(next!==fingerprint) { fingerprint=next; screen.renderAgain(); }
      } catch(error) {
        if(stopped || version!==requestVersion) return;
        needsRetry=true;
        screen.busy=true;
        screen.progress=error.message;
        screen.renderAgain();
      }
    }
    // Queue through api to retain the exact job sequence. operation() only
    // returns acceptance, so it cannot prove completion. No mutation is chained
    // in the browser: country preparation and group activation are server jobs.
    async function run(path, body, success) {
      if(pending || screen.busy) return false;
      pending=true; screen.busy=true;
      screen.progress=path==='geo/update' ? _('Downloading and validating GeoIP and GeoSite…') : _('Preparing routing…');
      screen.renderAgain();
      try {
        const job = await shared.api('routing/'+path,'POST',body);
        if(!job || !Number.isSafeInteger(job.sequence)) throw Error(errorText('operation_failed'));
        const end=Date.now()+16*60*1000;
        let observed=job;
        while(observed.running && Date.now()<end && !stopped) {
          await new Promise(resolve => setTimeout(resolve,750));
          if(stopped) return false;
          const state = await shared.api('state');
          acceptJob(state.job);
          observed=latestJob;
          if(!observed || observed.sequence!==job.sequence) throw Error(errorText('operation_failed'));
        }
        if(stopped) return false;
        if(observed.running) throw Error(errorText('geo_update_timeout'));
        if(!observed.succeeded) throw Error(errorText(observed.error || 'operation_failed'));
        if(success) notice(success);
        return true;
      } finally {
        pending=false; screen.busy=false; screen.progress='';
        await load();
        screen.renderAgain();
      }
    }
    async function action(path, body, success, failure) {
      try { return await run(path,body,success); }
      catch(error) { notice(failure+' '+error.message,true); return false; }
    }
    screen.handleToggle = event => {
      event?.preventDefault();
      const enabled=!(screen.settings.country_routing?.enabled && screen.settings.firewall?.enabled);
      return action('country',{country:screen.countryCode,enabled},enabled ? _('Local-country routing is on. LAN and the selected country go directly.') : _('Local-country routing is off.'),_('Could not change routing.'));
    };
    screen.handleCountryChange = event => {
      if(!event.target.value) return;
      return action('country',{country:event.target.value},_('Country saved.'),_('Could not save the country.'));
    };
    screen.handleGeoUpdate = () => action('geo/update',{},_('GeoIP and GeoSite are up to date.'),_('Could not update GeoIP and GeoSite.'));
    screen.handleRuleToggle = (name,event) => action('groups/toggle',{name,enabled:event.target.checked},event.target.checked ? _('Exclusion enabled.') : _('Exclusion disabled.'),_('Could not change the exclusion.'));
    screen.handleRuleDelete = (name,event) => {
      event?.preventDefault();
      if(screen.busy) return;
      return shared.confirmAction(_('Delete this exclusion? Traffic matching it will follow the regular VPN route.'), () => action('groups/delete',{name},_('Exclusion deleted.'),_('Could not delete the exclusion.')));
    };
    screen.handleRuleSubmit = async (rule,nameInput,domainsInput,cidrsInput,errorBox,submit,event) => {
      event?.preventDefault();
      const name=text(rule?.name || nameInput.value).toLowerCase();
      if(!/^[a-z][a-z0-9-]*$/.test(name)) { errorBox.textContent=_('Use lowercase Latin letters, digits, and hyphens; start with a letter.'); nameInput.focus(); return; }
      const domains=words(domainsInput.value), cidrs=words(cidrsInput.value);
      if(!domains.length && !cidrs.length && !rule?.services?.length) { errorBox.textContent=_('Add at least one domain or IP address.'); domainsInput.focus(); return; }
      submit.disabled=true;
      submit.textContent=rule ? _('Saving…') : _('Adding…');
      errorBox.textContent='';
      try {
        if(await run(rule ? 'groups/edit' : 'groups',{name,domains,cidrs},rule ? _('Exclusion saved.') : _('Exclusion added and enabled.'))) ui.hideModal();
      } catch(error) { errorBox.textContent=error.message; }
      finally { submit.disabled=false; submit.textContent=rule ? _('Save') : _('Add'); }
    };
    screen.handleImportCheck = async event => {
      event?.preventDefault();
      const link=screen.importValue || '';
      try {
        const profile=await shared.api('routing/happ/preview','POST',{link});
        if(stopped || screen.importValue!==link) return;
        screen.importProfile=profile; screen.importError=''; screen.renderAgain();
      } catch(error) { if(stopped || screen.importValue!==link) return; screen.importProfile=null; screen.importError=error.message; screen.renderAgain(); notice(_('Could not read the HAPP profile.'),true); }
    };
    screen.renderAgain();
    let refreshKey='';
    instance = {
      ready:load(),
      refresh: snapshot => {
        if(stopped || !snapshot) return;
        acceptJob(snapshot.job);
        const key=JSON.stringify([snapshot.status?.settings?.country_routing,snapshot.status?.settings?.firewall,snapshot.job]);
        if(key!==refreshKey || needsRetry) { refreshKey=key; void load(); }
      },
      destroy:() => { stopped=true; requestVersion++; ui.hideModal(); container.replaceChildren(); /* An accepted job stays on the server. */ }
    };
    return instance;
  }
  window.FastLaneRouting = {mount,refresh:snapshot=>instance?.refresh(snapshot),destroy:()=>{instance?.destroy();instance=null;}};
})({
  "The link must start with happ://routing/onadd/.": "Ссылка должна начинаться с happ://routing/onadd/.",
  "The link does not contain a routing profile.": "В ссылке нет профиля маршрутизации.",
  "Could not read Geo database status.": "Не удалось прочитать состояние Geo-баз.",
  "GeoIP and GeoSite update failed.": "Обновление GeoIP и GeoSite завершилось с ошибкой.",
  "GeoIP and GeoSite did not pass validation.": "GeoIP и GeoSite не прошли проверку.",
  "The update did not finish in time. It may still be running in the background.": "Не удалось дождаться завершения. Обновление может продолжаться в фоне.",
  "Choose a country first.": "Сначала выберите страну.",
  "Preparing routing…": "Готовлю маршрутизацию…",
  "Turning the rule off…": "Выключаю правило…",
  "Downloading and validating GeoIP and GeoSite…": "Скачиваю и проверяю GeoIP и GeoSite…",
  "Turning local-country routing on…": "Включаю маршрутизацию локальной страны…",
  "Local-country routing is on. LAN and the selected country go directly.": "Маршрутизация включена: LAN и выбранная страна идут напрямую.",
  "Local-country routing is off.": "Маршрутизация локальной страны выключена.",
  "Could not change routing.": "Не удалось изменить маршрутизацию.",
  "Applying the selected country…": "Применяю выбранную страну…",
  "Saving the selected country…": "Сохраняю выбранную страну…",
  "Country saved.": "Страна сохранена.",
  "Could not save the country.": "Не удалось сохранить страну.",
  "GeoIP and GeoSite are up to date.": "GeoIP и GeoSite обновлены.",
  "Could not update GeoIP and GeoSite.": "Не удалось обновить GeoIP и GeoSite.",
  "Exclusion enabled.": "Исключение включено.",
  "Exclusion disabled.": "Исключение выключено.",
  "Could not change the exclusion.": "Не удалось изменить исключение.",
  "Delete this exclusion? Traffic matching it will follow the regular VPN route.": "Удалить это исключение? Подходящий трафик снова пойдёт по обычному VPN-маршруту.",
  "Exclusion deleted.": "Исключение удалено.",
  "Could not delete the exclusion.": "Не удалось удалить исключение.",
  "Save": "Сохранить",
  "Add": "Добавить",
  "Edit exclusion": "Изменить исключение",
  "Add exclusion": "Добавить исключение",
  "Name": "Название",
  "Lowercase Latin letters, digits, and hyphens. The name cannot be changed later.": "Строчные латинские буквы, цифры и дефисы. Позже имя изменить нельзя.",
  "Domains": "Домены",
  "One domain per line. Subdomains are included automatically.": "Один домен на строку. Поддомены учитываются автоматически.",
  "IP addresses and networks": "IP-адреса и сети",
  "One IPv4 address, CIDR, or range per line.": "Один IPv4-адрес, CIDR или диапазон на строку.",
  "Cancel": "Отмена",
  "Use lowercase Latin letters, digits, and hyphens; start with a letter.": "Используйте строчные латинские буквы, цифры и дефисы; начните с буквы.",
  "Add at least one domain or IP address.": "Добавьте хотя бы один домен или IP-адрес.",
  "Saving…": "Сохраняю…",
  "Adding…": "Добавляю…",
  "Exclusion saved.": "Исключение сохранено.",
  "Exclusion added and enabled.": "Исключение добавлено и включено.",
  "Could not load exclusions.": "Не удалось загрузить исключения.",
  "No exclusions yet. Add a service or device cloud that must use the regular internet connection.": "Исключений пока нет. Добавьте сервис или облако устройства, которому нужен обычный интернет без VPN.",
  "domains": "доменов",
  "IP entries": "IP-адресов",
  "On": "Включено",
  "Off": "Выключено",
  "Edit": "Изменить",
  "Delete": "Удалить",
  "No domains": "Нет доменов",
  "No IP addresses": "Нет IP-адресов",
  "Direct access exclusions": "Исключения из VPN",
  "Traffic matching an enabled group bypasses VPN. Everything else follows the route above.": "Трафик включённой группы идёт напрямую, в обход VPN. Всё остальное следует маршруту выше.",
  "Could not read the HAPP profile.": "Не удалось прочитать HAPP-профиль.",
  "HAPP profile": "Профиль HAPP",
  "Detected: direct": "Распознано: напрямую",
  "through VPN": "через VPN",
  "blocked": "заблокировано",
  "The link is valid. Partial application is disabled until Fast Lane can apply custom direct, proxy, and block rules atomically.": "Ссылка читается. Частично применять её нельзя: Fast Lane ещё нужна атомарная поддержка custom direct/proxy/block-правил.",
  "Not selected": "Не выбрана",
  "Direct": "Напрямую",
  "Fast Lane routing is off": "Маршрутизация Fast Lane выключена",
  "Through VPN": "Через VPN",
  "Except the enabled exclusions below": "Кроме включённых исключений ниже",
  "By device": "По устройствам",
  "VPN is used only for selected devices": "VPN используется только для выбранных устройств",
  "By rule": "По правилам",
  "VPN is used only for selected destinations": "VPN используется только для выбранных направлений",
  "Routing": "Маршруты",
  "Choose which traffic goes directly and which goes through VPN. Geo databases are managed automatically.": "Выберите, какой трафик идёт напрямую, а какой через VPN. Geo-базы обновляются автоматически.",
  "Local-country traffic directly": "Трафик локальной страны напрямую",
  "LAN and traffic for the selected country bypass VPN. All other internet traffic follows the active Fast Lane routing policy.": "LAN и трафик выбранной страны идут в обход VPN. Остальной интернет следует активной политике маршрутизации Fast Lane.",
  "Country": "Страна",
  "Choose a country": "Выберите страну",
  "Home network": "Домашняя сеть",
  "Always direct": "Всегда напрямую",
  "Admin panel and local devices": "Админка и локальные устройства",
  "Managed GeoIP rule": "Управляемое правило GeoIP",
  "Rule is off": "Правило выключено",
  "Rest of the internet": "Остальной интернет",
  "Update Geo databases": "Обновить Geo-базы",
  "Install Geo databases": "Установить Geo-базы",
  "GeoIP and GeoSite are ready": "GeoIP и GeoSite готовы",
  "Databases will be installed automatically when routing is first enabled": "Базы установятся автоматически при первом включении маршрутизации",
  "Import and advanced rules": "Импорт и расширенные правила",
  "You can validate a HAPP link. Fast Lane shows its contents and never silently drops unsupported rules.": "Можно проверить ссылку в формате HAPP. Fast Lane покажет состав профиля и не будет молча отбрасывать неподдерживаемые правила.",
  "Validate link": "Проверить ссылку"
}, function(E, _, L, ui, countries) {
function trim(value) { return value == null ? '' : String(value).trim(); }
function list(value) { return Array.isArray(value) ? value.filter(function(item) { return trim(item) !== ''; }) : []; }
function tokens(value) { return trim(value).split(/[\s,;]+/).map(trim).filter(Boolean); }
function titleCase(value) {
	value = trim(value).replace(/-/g, ' ');
	return value ? value.charAt(0).toUpperCase() + value.slice(1) : value;
}

return {
customRules: function() {
		var services = Array.isArray(this.services) ? this.services : [];
		return services.filter(function(service) {
			return service && service.readonly !== true && trim(service.source) === 'custom';
		}).sort(function(a, b) { return trim(a.name).localeCompare(trim(b.name)); });
	},
bypassSettings: function() {
		var firewall = this.settings && this.settings.firewall || {};
		return firewall.split && firewall.split.bypass || {};
	},
isRuleActive: function(name) {
		return list(this.bypassSettings().services).indexOf(name) >= 0;
	},
handleRuleOpen: function(rule, ev) {
		if (ev) ev.preventDefault();
		if (this.busy) return;
		var editing = !!rule;
		var nameInput = E('input', { type: 'text', value: editing ? trim(rule.name) : '', placeholder: 'roborock', disabled: editing ? 'disabled' : null, autocomplete: 'off', spellcheck: 'false' });
		var domainsInput = E('textarea', { placeholder: 'roborock.com\nmiot-spec.org', spellcheck: 'false', autocapitalize: 'none' }, [ list(rule && rule.domains).join('\n') ]);
		var cidrsInput = E('textarea', { placeholder: '192.0.2.10\n192.0.2.0/24', spellcheck: 'false', autocapitalize: 'none' }, [ list(rule && rule.cidrs).join('\n') ]);
		domainsInput.value = list(rule && rule.domains).join('\n');
		cidrsInput.value = list(rule && rule.cidrs).join('\n');
		var errorBox = E('div', { class: 'flr-form-error', 'aria-live': 'polite' });
		var submit = E('button', { class: 'flr-modal-button flr-modal-primary fl-dialog-button fl-dialog-primary', type: 'button' }, [ editing ? _('Save') : _('Add') ]);
		submit.addEventListener('click', L.bind(this.handleRuleSubmit, this, rule || null, nameInput, domainsInput, cidrsInput, errorBox, submit));
		ui.showModal(editing ? _('Edit exclusion') : _('Add exclusion'), [
			E('div', { class: 'flr-rule-form fl-dialog-form' }, [
				E('label', { class: 'flr-form-field fl-dialog-field' }, [ E('span', { class: 'flr-form-label fl-dialog-label' }, [ _('Name') ]), nameInput, E('span', { class: 'flr-form-help fl-dialog-help' }, [ _('Lowercase Latin letters, digits, and hyphens. The name cannot be changed later.') ]) ]),
				E('label', { class: 'flr-form-field fl-dialog-field' }, [ E('span', { class: 'flr-form-label fl-dialog-label' }, [ _('Domains') ]), domainsInput, E('span', { class: 'flr-form-help fl-dialog-help' }, [ _('One domain per line. Subdomains are included automatically.') ]) ]),
				E('label', { class: 'flr-form-field fl-dialog-field' }, [ E('span', { class: 'flr-form-label fl-dialog-label' }, [ _('IP addresses and networks') ]), cidrsInput, E('span', { class: 'flr-form-help fl-dialog-help' }, [ _('One IPv4 address, CIDR, or range per line.') ]) ]),
				errorBox
			]),
			E('div', { class: 'right fl-dialog-actions' }, [ E('button', { class: 'flr-modal-button fl-dialog-button', type: 'button', click: ui.hideModal }, [ _('Cancel') ]), submit ])
		]);
		var modal = document.querySelector('.modal');
		if (modal) {
			modal.classList.add('fastlane-routing-modal');
			modal.classList.add('fl-dialog');
		}
		window.requestAnimationFrame(function() { (editing ? domainsInput : nameInput).focus(); });
	},
renderRuleValues: function(values, emptyText) {
		values = list(values);
		if (!values.length) return E('div', { class: 'flr-rule-empty' }, [ emptyText ]);
		return E('div', { class: 'flr-rule-values' }, values.map(function(value) { return E('code', { class: 'flr-rule-value' }, [ value ]); }));
	},
renderBypassRules: function() {
		var rules = this.customRules();
		var body = [];
		if (this.rulesError) body.push(E('div', { class: 'flr-bypass-error' }, [ _('Could not load exclusions.'), ' ', this.rulesError ]));
		if (!rules.length && !this.rulesError) body.push(E('div', { class: 'flr-bypass-empty' }, [ _('No exclusions yet. Add a service or device cloud that must use the regular internet connection.') ]));
		for (var i = 0; i < rules.length; i++) {
			var rule = rules[i];
			var active = this.isRuleActive(rule.name);
			var domainCount = list(rule.domains).length;
			var cidrCount = list(rule.cidrs).length;
			body.push(E('article', { class: 'flr-rule ' + (active ? 'flr-rule-active' : '') }, [
				E('div', { class: 'flr-rule-head' }, [
					E('div', { class: 'flr-rule-title' }, [ E('h3', {}, [ titleCase(rule.name) ]), E('div', { class: 'flr-rule-meta' }, [ domainCount + ' ' + _('domains') + ' · ' + cidrCount + ' ' + _('IP entries') ]) ]),
					E('label', { class: 'flr-rule-switch' }, [ E('input', { type: 'checkbox', checked: active ? 'checked' : null, disabled: this.busy ? 'disabled' : null, change: L.bind(this.handleRuleToggle, this, rule.name) }), E('span', { class: 'flr-rule-switch-track' }), E('span', { class: 'flr-rule-switch-label' }, [ active ? _('On') : _('Off') ]) ]),
					E('div', { class: 'flr-rule-actions' }, [ E('button', { class: 'flr-button', disabled: this.busy ? 'disabled' : null, click: ui.createHandlerFn(this, 'handleRuleOpen', rule) }, [ _('Edit') ]), E('button', { class: 'flr-button flr-button-danger', disabled: this.busy ? 'disabled' : null, click: ui.createHandlerFn(this, 'handleRuleDelete', rule.name) }, [ _('Delete') ]) ])
				]),
				E('div', { class: 'flr-rule-grid' }, [
					E('div', { class: 'flr-rule-column' }, [ E('div', { class: 'flr-rule-column-title' }, [ E('span', {}, [ _('Domains') ]), E('span', {}, [ String(domainCount) ]) ]), this.renderRuleValues(rule.domains, _('No domains')) ]),
					E('div', { class: 'flr-rule-column' }, [ E('div', { class: 'flr-rule-column-title' }, [ E('span', {}, [ _('IP addresses and networks') ]), E('span', {}, [ String(cidrCount) ]) ]), this.renderRuleValues(rule.cidrs, _('No IP addresses')) ])
				])
			]));
		}
		return E('section', { class: 'flr-bypass' }, [
			E('div', { class: 'flr-bypass-head' }, [ E('div', {}, [ E('h2', {}, [ _('Direct access exclusions') ]), E('p', {}, [ _('Traffic matching an enabled group bypasses VPN. Everything else follows the route above.') ]) ]), E('button', { class: 'flr-button flr-button-primary', disabled: this.busy ? 'disabled' : null, click: ui.createHandlerFn(this, 'handleRuleOpen', null) }, [ '+ ', _('Add exclusion') ]) ])
		].concat(body));
	},
renderImportPreview: function() {
		if (!this.importProfile) return this.importError ? E('div', { class: 'flr-preview' }, [ this.importError ]) : '';
		var profile = this.importProfile;
		var directCount = (profile.DirectSites || []).length + (profile.DirectIp || []).length;
		var proxyCount = (profile.ProxySites || []).length + (profile.ProxyIp || []).length;
		var blockCount = (profile.BlockSites || []).length + (profile.BlockIp || []).length;
		return E('div', { class: 'flr-preview' }, [
			E('strong', {}, [ trim(profile.Name) || _('HAPP profile') ]),
			E('div', {}, [ _('Detected: direct') + ' — ' + directCount + ', ' + _('through VPN') + ' — ' + proxyCount + ', ' + _('blocked') + ' — ' + blockCount + '.' ]),
			E('div', {}, [ _('The link is valid. Partial application is disabled until Fast Lane can apply custom direct, proxy, and block rules atomically.') ])
		]);
	},
renderContent: function() {
		var firewall = this.settings && this.settings.firewall || {};
		var countryRouting = this.settings && this.settings.country_routing || {};
		var enabled = countryRouting.enabled === true && firewall.enabled === true;
		var countryCode = this.countryCode || trim(countryRouting.country_code);
		var countryName = countryCode ? countries.name(countryCode) : _('Not selected');
		var firewallMode = trim(firewall.mode || 'disabled');
		var defaultAction = trim(firewall.split && firewall.split.default_action || 'direct');
		var restValue = _('Direct');
		var restNote = _('Fast Lane routing is off');
		if (firewall.enabled === true && firewallMode === 'split' && defaultAction === 'proxy') {
			restValue = _('Through VPN');
			restNote = _('Except the enabled exclusions below');
		} else if (firewall.enabled === true && firewallMode === 'hosts') {
			restValue = _('By device');
			restNote = _('VPN is used only for selected devices');
		} else if (firewall.enabled === true) {
			restValue = _('By rule');
			restNote = _('VPN is used only for selected destinations');
		}
		var geoReady = this.geodata && this.geodata.ready === true;
		return [
			E('div', { class: 'flr-head' }, [
				E('div', {}, [ E('h1', {}, [ _('Routing') ]), E('p', {}, [ _('Choose which traffic goes directly and which goes through VPN. Geo databases are managed automatically.') ]) ])
			]),
			E('section', { class: 'flr-control' }, [
				E('div', {}, [ E('h2', {}, [ _('Local-country traffic directly') ]), E('p', {}, [ _('LAN and traffic for the selected country bypass VPN. All other internet traffic follows the active Fast Lane routing policy.') ]) ]),
				E('div', { class: 'flr-control-actions' }, [
					E('label', { class: 'flr-country-label' }, [ _('Country'), E('select', { class: 'flr-select', disabled: this.busy ? 'disabled' : null, change: L.bind(this.handleCountryChange, this) }, [ E('option', { value: '', selected: countryCode ? null : 'selected' }, [ _('Choose a country') ]) ].concat(countries.options(countryCode))) ]),
					E('label', { class: 'flr-switch' }, [ E('input', { type: 'checkbox', checked: enabled ? 'checked' : null, disabled: this.busy || !countryCode ? 'disabled' : null, change: L.bind(this.handleToggle, this) }), E('span', { class: 'flr-switch-track' }), E('span', { class: 'flr-switch-label' }, [ enabled ? _('On') : _('Off') ]) ])
				])
			]),
			E('div', { class: 'flr-flow' }, [
				E('div', { class: 'flr-step' }, [ E('div', { class: 'flr-step-label' }, [ _('Home network') ]), E('div', { class: 'flr-step-value flr-ready' }, [ _('Always direct') ]), E('div', { class: 'flr-step-note' }, [ _('Admin panel and local devices') ]) ]),
				E('div', { class: 'flr-arrow', 'aria-hidden': 'true' }, [ '→' ]),
				E('div', { class: 'flr-step' }, [ E('div', { class: 'flr-step-label' }, [ countryName ]), E('div', { class: 'flr-step-value ' + (enabled ? 'flr-ready' : 'flr-warn') }, [ enabled ? _('Direct') : _('Through VPN') ]), E('div', { class: 'flr-step-note' }, [ enabled ? _('Managed GeoIP rule') + (countryCode === 'RU' || countryCode === 'CN' ? ' + GeoSite' : '') : _('Rule is off') ]) ]),
				E('div', { class: 'flr-arrow', 'aria-hidden': 'true' }, [ '→' ]),
				E('div', { class: 'flr-step' }, [ E('div', { class: 'flr-step-label' }, [ _('Rest of the internet') ]), E('div', { class: 'flr-step-value' }, [ restValue ]), E('div', { class: 'flr-step-note' }, [ restNote ]) ])
			]),
			E('div', { class: 'flr-actions' }, [
				E('button', { class: 'flr-button ' + (!geoReady ? 'flr-button-primary' : ''), disabled: this.busy ? 'disabled' : null, click: ui.createHandlerFn(this, 'handleGeoUpdate') }, [ geoReady ? _('Update Geo databases') : _('Install Geo databases') ]),
				E('span', { class: 'flr-progress', 'aria-live': 'polite' }, [ this.progress || (geoReady ? _('GeoIP and GeoSite are ready') : _('Databases will be installed automatically when routing is first enabled')) ])
			]),
			this.renderBypassRules(),
			E('details', { class: 'flr-advanced' }, [
				E('summary', {}, [ _('Import and advanced rules') ]),
				E('p', { class: 'flr-advanced-copy' }, [ _('You can validate a HAPP link. Fast Lane shows its contents and never silently drops unsupported rules.') ]),
				E('div', { class: 'flr-import' }, [ E('input', { class: 'flr-input', type: 'text', placeholder: 'happ://routing/onadd/…', value: this.importValue || '', input: L.bind(function(ev) { this.importValue = ev.target.value; }, this) }), E('button', { class: 'flr-button', click: ui.createHandlerFn(this, 'handleImportCheck') }, [ _('Validate link') ]) ]),
				this.renderImportPreview()
			])
		];
	},
};
});
