include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Fast Lane
LUCI_DEPENDS:=+rpcd-mod-file
LUCI_PKGARCH:=all
PKG_LICENSE:=MIT
PKG_MAINTAINER:=Alexey

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
