package openwrt_test

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/design-maestro/fastlane/internal/domain"
)

// This is an opt-in stability/continuity test, not a throughput benchmark or a
// prediction of NanoPi performance. It boots a NEW disposable QEMU guest only.
// All AWG keys are generated by configureAWGNamespaceStand inside that guest.
// No production router, subscriptions, credentials or existing guest is used.
//
// Required: FASTLANE_RUN_OPENWRT_INTEGRATION=1,
// FASTLANE_AWG_SOAK_DURATION=10m..24h, and FASTLANE_AWG_SOAK_REPORT set to a NEW
// absolute report pathname in an existing directory. Existing reports are never
// overwritten by a new run. The internal parent timeout is duration + 30m;
// provide at least another minute for the Go runner's cleanup deadline.
//
// For a 24h run which outlives the initiating tool turn, the CALLER can compile
// this package with go test -c, then run the resulting test binary with nohup,
// stdin from /dev/null, an explicit log path, -test.v,
// and working directory test/integration/openwrt (the shared harness resolves
// the repository root relative to that directory),
// -test.run='^TestOpenWrtAWGSoak$', and -test.timeout=25h. The JSON report is the
// monitoring contract; spawning a process is not a passed soak. SIGINT/SIGTERM
// cancel the VM and finalize failure; SIGKILL/power loss cannot run defers, so a
// stale running report is inconclusive, NEVER passed. No process is launched by
// ordinary go test, compile checks or the unit tests below.
//
// The requested soak interval begins AFTER setup/watcher stabilization. Its
// deadline is reported separately from the overall parent deadline. Cycles run
// at 2h, 4h, ... strictly before the soak deadline (11 cycles for exactly 24h).
// A 10m smoke exercises admission, setup, sampling and reporting, not a 2h cycle.
func TestOpenWrtAWGSoak(t *testing.T) {
	duration, enabled, err := parseAWGSoakDuration(os.Getenv("FASTLANE_AWG_SOAK_DURATION"))
	if err != nil {
		t.Fatal("invalid FASTLANE_AWG_SOAK_DURATION: require 10m through 24h")
	}
	if !enabled || os.Getenv("FASTLANE_RUN_OPENWRT_INTEGRATION") != "1" {
		t.Skip("requires explicit isolated AWG soak opt-in")
	}
	started := time.Now()
	parentLimit := duration + 30*time.Minute
	if deadline, ok := t.Deadline(); ok && deadline.Sub(started) < parentLimit+30*time.Second {
		t.Fatalf("runner timeout too short: use -timeout at least %s (25h for a 24h soak)", parentLimit+time.Minute)
	}
	report, err := newAWGSoakReport(os.Getenv("FASTLANE_AWG_SOAK_REPORT"), started, duration)
	if err != nil {
		t.Fatal("cannot initialize exclusive 0600 soak report; supply a new absolute path in an existing directory")
	}
	defer report.finish(t)
	signals, stopSignals := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stopSignals()
	ctx, cancel := context.WithTimeout(signals, parentLimit)
	defer cancel()
	// Even a setup helper which does not accept a context must not leave a
	// falsely running report after the outer deadline. This watcher never calls
	// testing.T or reads guest output. Join it before the final report write.
	stopWatch, watchDone := make(chan struct{}), make(chan struct{})
	go func() {
		defer close(watchDone)
		select {
		case <-stopWatch:
		case <-ctx.Done():
			code := "parent_cancelled"
			if errors.Is(ctx.Err(), context.DeadlineExceeded) {
				code = "parent_timeout"
			}
			_ = report.change(func(r *awgSoakProgress) { r.Status = "failed"; r.Errors = append(r.Errors, code) })
		}
	}()
	defer func() { close(stopWatch); <-watchDone }()
	fail := func(code string) {
		t.Helper()
		_ = report.change(func(r *awgSoakProgress) { r.Errors = append(r.Errors, code); r.Status = "failed" })
		t.Fatal("AWG soak failed: " + code)
	}
	phase := func(value string) {
		t.Helper()
		if ctx.Err() != nil {
			fail("parent_cancelled")
		}
		if err := report.change(func(r *awgSoakProgress) { r.CurrentPhase = value }); err != nil {
			fail("report_write_failed")
		}
	}
	run := func(code string, action func(context.Context) error) {
		t.Helper()
		phase(code)
		if err := action(ctx); err != nil {
			fail(code + "_failed")
		}
	}
	phase("create_guest")
	h, err := newOpenWRTHarness(t)
	if err != nil {
		fail("create_guest_failed")
	}
	defer h.Close()
	run("boot_guest", h.Start)
	run("install_base", func(ctx context.Context) error {
		return h.sshCommand(ctx, "opkg update && opkg install ca-bundle nftables kmod-nft-tproxy rpcd-mod-file")
	})
	run("install_dnsmasq_full", func(ctx context.Context) error {
		return h.sshCommand(ctx, "opkg list-installed | grep -q '^dnsmasq-full ' || opkg install dnsmasq-full >/dev/null 2>&1 || { opkg remove dnsmasq && opkg install dnsmasq-full; }")
	})
	run("install_fastlane", h.InstallFastLane)
	run("pause_daemon", h.PauseFastLaneDaemon)
	run("install_xray", h.InstallXray)
	run("install_awg", func(ctx context.Context) error { return installAWGStandPackages(ctx, h) })
	run("configure_awg_stand", func(ctx context.Context) error { return configureAWGNamespaceStand(ctx, h, false) })
	run("configure_checks", func(ctx context.Context) error {
		return h.sshCommand(ctx, fastlaneRemoteBinary+" firewall set bypass example.com && "+fastlaneRemoteBinary+" settings set refresh-interval 24h && "+fastlaneRemoteBinary+" settings set health-check-interval 0s")
	})
	run("import_check_connect_awg", func(ctx context.Context) error {
		return h.sshCommand(ctx, fastlaneRemoteBinary+" awg import --file /var/run/fastlane/test-client.conf --name 'Isolated AWG soak' && "+fastlaneRemoteBinary+" awg check && "+fastlaneRemoteBinary+" awg connect")
	})
	// Suppress unrelated scheduled pool checks, NOT the real connection watcher.
	// No subscriptions/reserve are added: AWG outage must select managed direct.
	run("start_watcher", func(ctx context.Context) error {
		return h.sshCommand(ctx, "FASTLANE_SCHEDULER_TICK=1h FASTLANE_MANAGEMENT_LISTEN=127.0.0.1:9080 service fastlane start")
	})
	phase("wait_watcher_http")
	oldDaemonPID, err := waitAWGSoakWatcher(ctx, h, "")
	if err != nil {
		fail("watcher_http_not_ready")
	}
	// A changed daemon PID AND its fresh HTTP listener prove RestoreRuntime
	// returned; merely rereading the old state file cannot satisfy readiness.
	run("warm_restart_watcher", func(ctx context.Context) error {
		return h.sshCommand(ctx, "FASTLANE_SCHEDULER_TICK=1h FASTLANE_MANAGEMENT_LISTEN=127.0.0.1:9080 service fastlane restart")
	})
	phase("wait_restored_watcher_http")
	if _, err := waitAWGSoakWatcher(ctx, h, oldDaemonPID); err != nil {
		fail("restored_watcher_http_not_ready")
	}
	phase("stabilize_watcher")
	readyCtx, readyCancel := context.WithTimeout(ctx, 3*time.Minute)
	var initial awgSoakSnapshot
	for readyCtx.Err() == nil {
		initial, err = readAWGSoakState(readyCtx, h)
		if err == nil && awgSoakActive(initial) {
			break
		}
		if !waitAWGSoak(readyCtx, time.Second) {
			break
		}
	}
	readyCancel()
	if err != nil || !awgSoakActive(initial) {
		fail("watcher_not_ready")
	}
	baseline, err := readAWGSoakPIDs(ctx, h)
	if err != nil {
		fail("baseline_pids_failed")
	}
	if err := sampleAWGSoak(ctx, h, baseline, initial.State.SelectedOutboundTag, "awg"); err != nil {
		fail(err.Error())
	}
	soakStarted := time.Now()
	soakDeadline := soakStarted.Add(duration)
	if err := report.change(func(r *awgSoakProgress) {
		r.SoakStartedAt = soakStarted.UTC()
		r.Deadline = soakDeadline.UTC()
		r.CurrentPhase = "steady_awg"
		r.Samples++
		r.LastSampleAt = soakStarted.UTC()
	}); err != nil {
		fail("report_write_failed")
	}
	fmt.Printf("AWG soak started: duration=%s; isolated QEMU; samples use proxy HTTPS and router DNS\n", duration)
	nextSample, nextCycle, nextHour := soakStarted.Add(time.Minute), soakStarted.Add(2*time.Hour), soakStarted.Add(time.Hour)
	statePhase := "steady_awg"
	lastNormalSampleWall := soakStarted.UTC()
	var transitionDeadline time.Time
	checkSample := func(mode string) {
		t.Helper()
		sampleStartedWall := time.Now().UTC()
		if err := sampleAWGSoak(ctx, h, baseline, initial.State.SelectedOutboundTag, mode); err != nil {
			fail(err.Error())
		}
		// Also check across the probe itself before advancing the last-sample
		// timestamp: sleeping inside a successful SSH/curl must not erase a gap.
		if err := validateAWGSoakSampleGap(time.Now().UTC(), sampleStartedWall, false); err != nil {
			fail("sample_wall_gap")
		}
		if err := validateAWGSoakSampleGap(time.Now().UTC(), lastNormalSampleWall, statePhase != "steady_awg"); err != nil {
			fail(err.Error())
		}
		if err := report.change(func(r *awgSoakProgress) { r.Samples++; r.LastSampleAt = time.Now().UTC() }); err != nil {
			fail("report_write_failed")
		}
		if mode == "awg" {
			lastNormalSampleWall = time.Now().UTC()
		}
	}
	command := func(script, code string) {
		t.Helper()
		c, stop := context.WithTimeout(ctx, 20*time.Second)
		defer stop()
		if err := h.sshCommand(c, script); err != nil {
			fail(code)
		}
	}
	for {
		if ctx.Err() != nil {
			fail("parent_cancelled")
		}
		now := time.Now()
		// UTC removes Go's monotonic component: a host sleep must be detected
		// even on platforms whose monotonic clock pauses during sleep. Check
		// BEFORE the final deadline branch so waking after 24h cannot pass.
		if err := validateAWGSoakSampleGap(now.UTC(), lastNormalSampleWall, statePhase != "steady_awg"); err != nil {
			fail(err.Error())
		}
		if !now.Before(soakDeadline) && statePhase == "steady_awg" {
			checkSample("awg")
			break
		}
		if statePhase == "steady_awg" && !now.Before(nextSample) {
			// Do not silently skip minute samples if the guest or host stalls.
			if now.Sub(nextSample) >= time.Minute {
				fail("sample_schedule_overrun")
			}
			checkSample("awg")
			nextSample = nextSample.Add(time.Minute)
		}
		if !now.Before(nextHour) {
			r := report.snapshot()
			fmt.Printf("AWG soak hourly: elapsed=%s samples=%d failure_cycles=%d phase=%s\n", time.Since(soakStarted).Round(time.Second), r.Samples, r.FailureCycles, statePhase)
			nextHour = nextHour.Add(time.Hour)
		}
		if statePhase == "steady_awg" && !now.Before(nextCycle) && now.Before(soakDeadline) {
			phase("waiting_direct")
			if err := report.change(func(r *awgSoakProgress) { r.FailureCyclesStarted++ }); err != nil {
				fail("report_write_failed")
			}
			fmt.Printf("AWG soak cycle %d: server down\n", report.snapshot().FailureCyclesStarted)
			statePhase = "waiting_direct"
			transitionDeadline = time.Now().UTC().Add(2 * time.Minute)
			command("ip netns exec awgserver ip link set awgsrv down", "server_down_failed")
		}
		if statePhase != "steady_awg" {
			mode := "direct"
			if statePhase == "waiting_awg" {
				mode = "awg"
			}
			retry, fatal := probeAWGSoakTransition(ctx, transitionDeadline, time.Now, func(probeCtx context.Context) error {
				return sampleAWGSoak(probeCtx, h, baseline, initial.State.SelectedOutboundTag, mode)
			})
			if retry != nil {
				if err := report.change(func(r *awgSoakProgress) {
					r.TransitionRetries++
					r.LastTransitionError = retry.Error()
					r.LastTransitionErrorAt = time.Now().UTC()
					r.LastTransitionErrorPhase = statePhase
				}); err != nil {
					fail("report_write_failed")
				}
			}
			if fatal != nil {
				fail(statePhase + "_" + fatal.Error())
			}
			if retry == nil {
				if err := report.change(func(r *awgSoakProgress) { r.Samples++; r.LastSampleAt = time.Now().UTC() }); err != nil {
					fail("report_write_failed")
				}
			}
			if retry == nil && statePhase == "waiting_direct" {
				fmt.Printf("AWG soak cycle %d: direct HTTPS/DNS and PID continuity verified; server up\n", report.snapshot().FailureCyclesStarted)
				phase("waiting_awg")
				statePhase = "waiting_awg"
				transitionDeadline = time.Now().UTC().Add(2 * time.Minute)
				command("ip netns exec awgserver ip link set awgsrv up", "server_up_failed")
			} else if retry == nil && statePhase == "waiting_awg" {
				if err := report.change(func(r *awgSoakProgress) { r.FailureCycles++; r.CurrentPhase = "steady_awg" }); err != nil {
					fail("report_write_failed")
				}
				fmt.Printf("AWG soak cycle %d: automatic AWG recovery verified\n", report.snapshot().FailureCycles)
				statePhase = "steady_awg"
				lastNormalSampleWall = time.Now().UTC()
				nextSample = time.Now().Add(time.Minute)
				nextCycle = nextCycle.Add(2 * time.Hour)
			}
		}
		// Transition probes replace minute samples only inside each bounded
		// 120s wall-clock window. Steady samples remain strict and never retry.
		if !waitAWGSoak(ctx, time.Second) {
			fail("parent_cancelled")
		}
	}
	if err := report.change(func(r *awgSoakProgress) { r.CurrentPhase = "complete" }); err != nil {
		fail("report_write_failed")
	}
	report.completed = true // finish() publishes passed only after normal return.
	fmt.Printf("AWG soak complete: elapsed=%s samples=%d failure_cycles=%d; no throughput claim\n", time.Since(soakStarted).Round(time.Second), report.snapshot().Samples, report.snapshot().FailureCycles)
}

// retry records a sanitized transient failure; fatal terminates the leg. Both
// may be set if a failed probe exhausted its wall-clock budget. Even a successful
// late probe cannot confirm recovery (including host sleep during SSH).
func probeAWGSoakTransition(parent context.Context, deadline time.Time, clock func() time.Time, probe func(context.Context) error) (retry, fatal error) {
	started := clock().UTC()
	deadline = deadline.UTC()
	if parent.Err() != nil {
		return nil, errors.New("parent_cancelled")
	}
	if !started.Before(deadline) {
		return nil, errors.New("timeout")
	}
	ctx, cancel := context.WithTimeout(parent, deadline.Sub(started))
	defer cancel()
	err := probe(ctx)
	if err != nil {
		switch err.Error() {
		case "watcher_http_failed", "status_read_failed", "status_decode_failed", "manual_connection_state_mismatch", "balancer_read_failed", "actual_balancer_mismatch", "proxy_https_failed", "router_dns_failed", "pids_read_failed", "balancer_changed_during_sample":
			retry = err
		case "managed_process_restarted":
			return nil, err // PID continuity is never a recoverable mismatch.
		default:
			return nil, errors.New("unexpected_probe_failure")
		}
	}
	finished := clock().UTC()
	if finished.Before(started) {
		return retry, errors.New("wall_clock_reversed")
	}
	if parent.Err() != nil {
		return retry, errors.New("parent_cancelled")
	}
	if !finished.Before(deadline) || ctx.Err() != nil {
		return retry, errors.New("timeout")
	}
	return retry, nil
}

func TestAWGSoakTransitionBudget(t *testing.T) {
	start := time.Now().UTC()
	for _, tc := range []struct {
		name       string
		elapsed    time.Duration
		probeError string
		wantRetry  bool
		wantFatal  string
	}{
		{"stable", time.Second, "", false, ""},
		{"state_transient", time.Second, "manual_connection_state_mismatch", true, ""},
		{"tag_changed", time.Second, "balancer_changed_during_sample", true, ""},
		{"https_transient", time.Second, "proxy_https_failed", true, ""},
		{"dns_transient", time.Second, "router_dns_failed", true, ""},
		{"pid_restart", time.Second, "managed_process_restarted", false, "managed_process_restarted"},
		{"last_in_budget", 120*time.Second - time.Nanosecond, "", false, ""},
		{"deadline_success_rejected", 120 * time.Second, "", false, "timeout"},
		{"deadline_error_recorded", 120 * time.Second, "actual_balancer_mismatch", true, "timeout"},
		{"host_sleep", 6 * time.Minute, "", false, "timeout"},
		{"clock_reversed", -time.Second, "", false, "wall_clock_reversed"},
		{"unknown_sanitized", time.Second, "private raw output", false, "unexpected_probe_failure"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			now := start
			retry, fatal := probeAWGSoakTransition(context.Background(), start.Add(120*time.Second), func() time.Time { return now }, func(ctx context.Context) error {
				deadline, ok := ctx.Deadline()
				if !ok || time.Until(deadline) > 120*time.Second {
					t.Fatal("probe is not bounded")
				}
				now = start.Add(tc.elapsed)
				if tc.probeError != "" {
					return errors.New(tc.probeError)
				}
				return nil
			})
			if (retry != nil) != tc.wantRetry {
				t.Fatalf("retry=%v", retry)
			}
			gotFatal := ""
			if fatal != nil {
				gotFatal = fatal.Error()
			}
			if gotFatal != tc.wantFatal {
				t.Fatalf("fatal=%q want=%q", gotFatal, tc.wantFatal)
			}
		})
	}
	t.Run("expired_does_not_probe", func(t *testing.T) {
		_, fatal := probeAWGSoakTransition(context.Background(), start, func() time.Time { return start }, func(context.Context) error { t.Fatal("expired probe ran"); return nil })
		if fatal == nil || fatal.Error() != "timeout" {
			t.Fatalf("fatal=%v", fatal)
		}
	})
	t.Run("cancelled_success_cannot_confirm", func(t *testing.T) {
		ctx, cancel := context.WithCancel(context.Background())
		defer cancel()
		_, fatal := probeAWGSoakTransition(ctx, start.Add(120*time.Second), func() time.Time { return start }, func(context.Context) error { cancel(); return nil })
		if fatal == nil || fatal.Error() != "parent_cancelled" {
			t.Fatalf("fatal=%v", fatal)
		}
	})
}

func parseAWGSoakDuration(raw string) (time.Duration, bool, error) {
	if raw == "" {
		return 0, false, nil
	}
	d, err := time.ParseDuration(raw)
	if err != nil || d < 10*time.Minute || d > 24*time.Hour {
		return 0, false, errors.New("invalid_soak_duration")
	}
	return d, true, nil
}

func waitAWGSoak(ctx context.Context, d time.Duration) bool {
	timer := time.NewTimer(d)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return false
	case <-timer.C:
		return true
	}
}

func validateAWGSoakSampleGap(now, last time.Time, controlled bool) error {
	if controlled {
		return nil
	} // controlled transitions have their own WALL deadline
	gap := now.Round(0).Sub(last.Round(0))
	if gap > 5*time.Minute {
		return errors.New("normal_sample_wall_gap")
	}
	if gap < 0 {
		return errors.New("wall_clock_reversed")
	}
	return nil
}

func waitAWGSoakWatcher(parent context.Context, h *openWRTHarness, previous string) (string, error) {
	ctx, cancel := context.WithTimeout(parent, 3*time.Minute)
	defer cancel()
	for ctx.Err() == nil {
		probeCtx, stop := context.WithTimeout(ctx, 10*time.Second)
		output, err := h.sshOutput(probeCtx, `set -eu; pid=$(pidof fastlane); test -n "$pid"; code=$(curl -sS --max-time 2 -o /dev/null -w '%{http_code}' http://127.0.0.1:9080/api/v1/state); test "$code" = 200; printf '%s\n' "$pid"`)
		stop()
		pid := strings.TrimSpace(string(output))
		parsed, parseErr := strconv.Atoi(pid)
		if err == nil && parseErr == nil && parsed > 0 && pid != previous {
			return pid, nil
		}
		if !waitAWGSoak(ctx, time.Second) {
			break
		}
	}
	return "", errors.New("watcher_http_not_ready")
}

// Keep these predicates local: the independent VLESS reserve acceptance test
// neither runs nor owns the AWG-only soak's acceptance criteria.
type awgSoakSnapshot struct {
	State    domain.RuntimeState `json:"state"`
	Settings domain.Settings     `json:"settings"`
}

func awgSoakManual(s awgSoakSnapshot) bool {
	return s.State.Mode == domain.SelectionModeManual && s.Settings.Mode == domain.SelectionModeManual && !s.Settings.AutoMode && s.State.AutoScope == ""
}

func awgSoakDirect(s awgSoakSnapshot) bool {
	return awgSoakManual(s) && !s.State.Connected && s.State.OperationalMode == domain.OperationalModeDirect && s.State.SelectedOutboundTag == "fastlane-direct" && s.State.CurrentOperation == nil
}

func awgSoakActive(s awgSoakSnapshot) bool {
	return awgSoakManual(s) && s.State.Connected && s.State.ActiveConnectionKind == "amneziawg" && s.State.OperationalMode == domain.OperationalModeVPN && s.State.CurrentOperation == nil && s.State.SelectedOutboundTag != "" && s.State.SelectedOutboundTag != "fastlane-direct"
}

func readAWGSoakState(parent context.Context, h *openWRTHarness) (awgSoakSnapshot, error) {
	ctx, cancel := context.WithTimeout(parent, 10*time.Second)
	defer cancel()
	var s awgSoakSnapshot
	output, err := h.sshOutput(ctx, fastlaneRemoteBinary+" --json status")
	if err != nil {
		return s, errors.New("status_read_failed")
	}
	if json.Unmarshal(output, &s) != nil {
		return s, errors.New("status_decode_failed")
	}
	return s, nil
}

func readAWGSoakPIDs(parent context.Context, h *openWRTHarness) (string, error) {
	ctx, cancel := context.WithTimeout(parent, 10*time.Second)
	defer cancel()
	output, err := h.sshOutput(ctx, `set -eu; pid=$(cat /var/run/xray.pid); kill -0 "$pid"; printf 'xray=%s\n' "$pid"; pids=$(pidof dnsmasq); test -n "$pids"; printf '%s\n' "$pids" | tr ' ' '\n' | sort -n`)
	if err != nil {
		return "", errors.New("pids_read_failed")
	}
	value := strings.TrimSpace(string(output))
	if value == "" {
		return "", errors.New("pids_read_failed")
	}
	return value, nil
}

func sampleAWGSoak(parent context.Context, h *openWRTHarness, baseline, awgTag, mode string) error {
	ctx, cancel := context.WithTimeout(parent, 50*time.Second)
	defer cancel()
	if err := h.sshCommand(ctx, `code=$(curl -sS --max-time 2 -o /dev/null -w '%{http_code}' http://127.0.0.1:9080/api/v1/state) || exit 1; test "$code" = 200`); err != nil {
		return errors.New("watcher_http_failed")
	}
	s, err := readAWGSoakState(ctx, h)
	if err != nil {
		return err
	}
	isAWG := awgSoakActive(s) && s.State.SelectedOutboundTag == awgTag
	isDirect := awgSoakDirect(s)
	if (mode == "awg" && !isAWG) || (mode == "direct" && !isDirect) || (mode == "transition" && !isAWG && !isDirect) {
		return errors.New("manual_connection_state_mismatch")
	}
	output, err := h.sshOutput(ctx, "xray api bi --server=127.0.0.1:10085 --json fastlane-main")
	if err != nil {
		return errors.New("balancer_read_failed")
	}
	var balancer struct {
		Balancer struct {
			Override struct {
				Target string `json:"target"`
			} `json:"override"`
		} `json:"balancer"`
	}
	if json.Unmarshal(output, &balancer) != nil || balancer.Balancer.Override.Target != s.State.SelectedOutboundTag {
		return errors.New("actual_balancer_mismatch")
	}
	// Trust certificate validation and the explicitly selected proxy. Neither
	// curl environment proxy exemptions nor a transparent LAN fixture can turn
	// this into a successful direct-connect probe by accident.
	if err := h.sshCommand(ctx, "curl -4 -fsS --max-time 20 --noproxy '' --proxy http://127.0.0.1:10809 https://cp.cloudflare.com/generate_204 -o /dev/null"); err != nil {
		return errors.New("proxy_https_failed")
	}
	if err := h.sshCommand(ctx, `answer=$(dig +time=5 +tries=1 +short @127.0.0.1 example.com A) || exit 1; printf '%s\n' "$answer" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'`); err != nil {
		return errors.New("router_dns_failed")
	}
	pids, err := readAWGSoakPIDs(ctx, h)
	if err != nil {
		return err
	}
	if pids != baseline {
		return errors.New("managed_process_restarted")
	}
	// A watcher switch during the requests must not turn an AWG sample into a
	// successful direct sample. Require the same actual selection after HTTPS
	// and DNS as before them; the next loop can observe a completed transition.
	output, err = h.sshOutput(ctx, "xray api bi --server=127.0.0.1:10085 --json fastlane-main")
	if err != nil {
		return errors.New("balancer_read_failed")
	}
	if json.Unmarshal(output, &balancer) != nil || balancer.Balancer.Override.Target != s.State.SelectedOutboundTag {
		return errors.New("balancer_changed_during_sample")
	}
	return nil
}

type awgSoakProgress struct {
	ProcessID                int       `json:"pid"`
	Status                   string    `json:"status"`
	CurrentPhase             string    `json:"current_phase"`
	Start                    time.Time `json:"start"`
	Deadline                 time.Time `json:"deadline"`
	ParentDeadline           time.Time `json:"parent_deadline"`
	SoakStartedAt            time.Time `json:"soak_started_at,omitempty"`
	UpdatedAt                time.Time `json:"updated_at"`
	LastSampleAt             time.Time `json:"last_sample_at"`
	SoakElapsedSeconds       int64     `json:"soak_elapsed_seconds"`
	ElapsedSeconds           int64     `json:"elapsed_seconds"`
	RequestedSeconds         int64     `json:"requested_seconds"`
	Samples                  int       `json:"samples"`
	FailureCycles            int       `json:"failure_cycles"`
	FailureCyclesStarted     int       `json:"failure_cycles_started"`
	TransitionRetries        int       `json:"transition_retries"`
	LastTransitionError      string    `json:"last_transition_error,omitempty"`
	LastTransitionErrorAt    time.Time `json:"last_transition_error_at,omitempty"`
	LastTransitionErrorPhase string    `json:"last_transition_error_phase,omitempty"`
	Errors                   []string  `json:"errors"`
}

type awgSoakReport struct {
	mu        sync.Mutex
	path      string
	progress  awgSoakProgress
	completed bool // owned only by the testing goroutine
}

func newAWGSoakReport(path string, start time.Time, duration time.Duration) (*awgSoakReport, error) {
	if !filepath.IsAbs(path) || filepath.Clean(path) != path {
		return nil, errors.New("report_path_invalid")
	}
	r := &awgSoakReport{path: path, progress: awgSoakProgress{ProcessID: os.Getpid(), Status: "running", CurrentPhase: "initializing", Start: start.UTC(), Deadline: start.Add(duration + 30*time.Minute).UTC(), ParentDeadline: start.Add(duration + 30*time.Minute).UTC(), RequestedSeconds: int64(duration / time.Second), Errors: []string{}}}
	if err := r.write(true); err != nil {
		return nil, err
	}
	return r, nil
}

func (r *awgSoakReport) snapshot() awgSoakProgress {
	r.mu.Lock()
	defer r.mu.Unlock()
	p := r.progress
	p.Errors = append([]string{}, p.Errors...)
	return p
}
func (r *awgSoakReport) change(apply func(*awgSoakProgress)) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	apply(&r.progress)
	return r.write(false)
}
func (r *awgSoakReport) finish(t *testing.T) {
	t.Helper()
	err := r.change(func(p *awgSoakProgress) {
		if t.Failed() || !r.completed || p.Status == "failed" {
			p.Status = "failed"
			if len(p.Errors) == 0 {
				p.Errors = append(p.Errors, "test_did_not_complete")
			}
		} else {
			p.Status = "passed"
		}
	})
	if err != nil {
		t.Error("soak_report_finalize_failed")
	}
}

// Atomic replacement in the same directory, with fsync before/after publishing
// and 0600 on every new inode. Initial Link publishes exclusively: another run
// or a preexisting file/symlink cannot be silently overwritten at admission.
func (r *awgSoakReport) write(initial bool) error {
	r.progress.UpdatedAt = time.Now().UTC()
	r.progress.ElapsedSeconds = int64(time.Since(r.progress.Start) / time.Second)
	if !r.progress.SoakStartedAt.IsZero() {
		r.progress.SoakElapsedSeconds = int64(time.Since(r.progress.SoakStartedAt) / time.Second)
	}
	data, err := json.MarshalIndent(r.progress, "", "  ")
	if err != nil {
		return errors.New("report_encode_failed")
	}
	if !initial {
		info, err := os.Lstat(r.path)
		if err != nil || !info.Mode().IsRegular() {
			return errors.New("report_target_changed")
		}
	}
	f, err := os.CreateTemp(filepath.Dir(r.path), ".awg-soak-*.tmp")
	if err != nil {
		return errors.New("report_temp_failed")
	}
	name := f.Name()
	defer os.Remove(name)
	if err = f.Chmod(0600); err == nil {
		_, err = f.Write(append(data, '\n'))
	}
	if err == nil {
		err = f.Sync()
	}
	closeErr := f.Close()
	if err != nil || closeErr != nil {
		return errors.New("report_write_failed")
	}
	if initial {
		err = os.Link(name, r.path)
	} else {
		err = os.Rename(name, r.path)
	}
	if err != nil {
		return errors.New("report_publish_failed")
	}
	dir, err := os.Open(filepath.Dir(r.path))
	if err != nil {
		return errors.New("report_directory_failed")
	}
	defer dir.Close()
	if err := dir.Sync(); err != nil {
		return errors.New("report_sync_failed")
	}
	return nil
}

func TestAWGSoakDurationValidation(t *testing.T) {
	for _, test := range []struct {
		raw              string
		want             time.Duration
		enabled, invalid bool
	}{
		{"", 0, false, false}, {"10m", 10 * time.Minute, true, false}, {"24h", 24 * time.Hour, true, false},
		{"2h30m", 150 * time.Minute, true, false}, {"0", 0, false, true}, {"9m59s", 0, false, true},
		{"24h1ns", 0, false, true}, {"-10m", 0, false, true}, {"tomorrow", 0, false, true}, {" 10m", 0, false, true},
	} {
		d, on, err := parseAWGSoakDuration(test.raw)
		if d != test.want || on != test.enabled || (err != nil) != test.invalid {
			t.Fatalf("duration case %q: %s %t %v", test.raw, d, on, err)
		}
	}
}

func TestAWGSoakAtomicReport(t *testing.T) {
	path := filepath.Join(t.TempDir(), "progress.json")
	r, err := newAWGSoakReport(path, time.Now(), 10*time.Minute)
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 3; i++ {
		if err := r.change(func(p *awgSoakProgress) { p.Samples++; p.CurrentPhase = "steady_awg" }); err != nil {
			t.Fatal(err)
		}
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var p awgSoakProgress
	if json.Unmarshal(data, &p) != nil || p.Samples != 3 || p.Status != "running" || len(p.Errors) != 0 {
		t.Fatal("invalid progress")
	}
	if p.ProcessID != os.Getpid() || p.SoakElapsedSeconds != 0 || !p.SoakStartedAt.IsZero() {
		t.Fatal("setup counted as soak or process ID missing")
	}
	info, err := os.Stat(path)
	if err != nil || info.Mode().Perm() != 0600 {
		t.Fatal("report permissions")
	}
	if _, err := newAWGSoakReport(path, time.Now(), 10*time.Minute); err == nil {
		t.Fatal("another run overwrote a report")
	}
	if _, err := newAWGSoakReport("relative.json", time.Now(), 10*time.Minute); err == nil {
		t.Fatal("relative report accepted")
	}
	link := filepath.Join(t.TempDir(), "linked.json")
	if err := os.Symlink(path, link); err != nil {
		t.Fatal(err)
	}
	if _, err := newAWGSoakReport(link, time.Now(), 10*time.Minute); err == nil {
		t.Fatal("symlink report accepted")
	}
	r.completed = true
	r.finish(t)
	data, err = os.ReadFile(path)
	if err != nil || json.Unmarshal(data, &p) != nil || p.Status != "passed" {
		t.Fatal("success not finalized")
	}
}

func TestAWGSoakWallClockGap(t *testing.T) {
	start := time.Now().UTC()
	for _, test := range []struct {
		gap                 time.Duration
		controlled, invalid bool
	}{
		{time.Minute, false, false}, {5 * time.Minute, false, false},
		{5*time.Minute + time.Nanosecond, false, true}, {24 * time.Hour, false, true},
		{6 * time.Minute, true, false}, {-time.Second, false, true},
	} {
		if err := validateAWGSoakSampleGap(start.Add(test.gap), start, test.controlled); (err != nil) != test.invalid {
			t.Fatalf("gap case %+v: %v", test, err)
		}
	}
}

func TestAWGSoakFailNowChild(t *testing.T) {
	path := os.Getenv("FASTLANE_AWG_SOAK_TEST_FAILNOW_REPORT")
	if path == "" {
		return
	}
	r, err := newAWGSoakReport(path, time.Now(), 10*time.Minute)
	if err != nil {
		t.Fatal("child_report_failed")
	}
	defer r.finish(t)
	t.Fatal("intentional sanitized FailNow fixture")
}

func TestAWGSoakFailNowReport(t *testing.T) {
	path := filepath.Join(t.TempDir(), "failed.json")
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, os.Args[0], "-test.run=^TestAWGSoakFailNowChild$")
	cmd.Env = append(os.Environ(), "FASTLANE_AWG_SOAK_TEST_FAILNOW_REPORT="+path)
	if err := cmd.Run(); err == nil {
		t.Fatal("child did not fail")
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var p awgSoakProgress
	if json.Unmarshal(data, &p) != nil || p.Status != "failed" || len(p.Errors) != 1 || p.Errors[0] != "test_did_not_complete" {
		t.Fatal("FailNow did not finalize report")
	}
}
